env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Kernel Build"
  timeout_in: 60m
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Install-Dependencies_script:
      - ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
      - pacman -Sy --noconfirm git bc inetutils python3 flex bison libc++ libxml2 python-pip zip wget cpio jdk-openjdk tzdata && python3 -m pip install networkx && pip3 install --upgrade gupload
      
  Clone-Sources_script:
      - git clone --single-branch --depth=1 https://github.com/nerdprojectorg/android_kernel_asus_sdm660 -b topaz-standalone kernel
      - git clone --single-branch --depth=1 https://github.com/nerdprojectorg/AnyKernel3.git -b master kernel/AnyKernel3
      - git clone --single-branch --depth=1 https://gitlab.com/RyuujiX/neutron-clang -b Neutron-16 kernel/clang
      
  Build-Kernel_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/z3zens/Kernel-CirrusCI/main/build.sh)"
